
const data = {
    products: [
        {
            // _id: "1",
            name: "Giant Rincon Mountain Bicycle",
            slug: "giant-rincon-mountain-bicycle",
            category: "Bicycle",
            image: "/images/p1.jpg",
            price: 100,
            countInStock: 10,
            brand: "Giant",
            rating: 4.5,
            numReviews: 5,
            description: "high quality bicycle",
        },
        {
            // _id: "2",
            name: "Specialized Pitch 650B Bicycle",
            slug: "specialized-pitch-650b-bicycle",
            category: "Bicycle",
            image: "/images/p2.jpg",
            price: 259,
            countInStock: 20,
            brand: "Specialized",
            rating: 3.7,
            numReviews: 55,
            description: "high quality bicycle",
        },
        {
            // _id: "3",
            name: "Xiaomi M365 PRO Electric Scooter",
            slug: "xiaomi-m365-pro-electric-scooter",
            category: "Scooter",
            image: "/images/p3.jpg",
            price: 200,
            countInStock: 5,
            brand: "Xiaomi",
            rating: 4.5,
            numReviews: 15,
            description: "high quality scooter",
        },
        {
            // _id: "4",
            name: "Xiaomi Mitu Rabbit Scooter",
            slug: "xiaomi-mitu-rabbit-scooter",
            category: "Scooter",
            image: "/images/p4.jpg",
            price: 100,
            countInStock: 10,
            brand: "Xiaomi",
            rating: 4.2,
            numReviews: 25,
            description: "high quality scooter",
        },
        {
            // _id: "5",
            name: "Nokia Mitu Rabbit Scooter",
            slug: "xiaomi-mitu-rabbit-scooter",
            category: "Scooter",
            image: "/images/p4.jpg",
            price: 100,
            countInStock: 10,
            brand: "Xiaomi",
            rating: 4,
            numReviews: 25,
            description: "high quality scooter",
        },
        {
            // _id: "6",
            name: "Samsung Rabbit Scooter",
            slug: "xiaomi-mitu-rabbit-scooter",
            category: "Scooter",
            image: "/images/p4.jpg",
            price: 100,
            countInStock: 10,
            brand: "Xiaomi",
            rating: 2,
            numReviews: 25,
            description: "high quality scooter",
        },
    ]
}

export default data;